### PR TITLE
Use Dockerfile build to make it work OOTB (chmod  in entrypoint.sh)

### PR DESCRIPTION
**Pull request by rfay**
This one changes the entrypoint.sh to do the chmod for us. 

It seems to work just fine.

### CODE REVIEW

**Comment by gilbertsoft** [comment]
Very like this solution. Only drawback is to have such a big entry point file to maintain. Wouldn't it be possible to introduce a new one and after fixing the permissions to forward to the existing one? Disclaimer, did not have a look at the existing scripts.

**Comment by rfay** [comment]
The entrypoint file isn't to be maintained, it's from the image repo, and has one line added to it. Yes, it's unfortunate, and the organization of the image repo doesn't make it easy to find. We should probably add it directly from the image repo though, that would be better. But then it would have to have that one line added.

**Comment by rfay** [comment]
The docker-entrypoint.sh comes from https://github.com/arangodb/arangodb-docker/blob/official/alpine/3.10.2/docker-entrypoint.sh

It would probably be good to figure out how to curl the one with the right version and then add the line to it. 

https://github.com/rpkoller/ddev-spidergram/pull/5/files#diff-a57c38e6fda3b5951fafea8537e6b7baec19818f0ca59cf2a7b03b0ba3780845R39

**Comment by rpkoller** [comment]
I've tested the following PR locally. Everything works out of the box now. awesome! 

I agree with @gilbertsoft that adding the whole entrypoint.sh might be sort of a maintenance burden. also the case the arangodb images changes. therefore a followup to improve the way the chmod is added to the entrypoint would be definitely desirable. but i would merge this PR for now to see how github actions likes the changes and if everything will run through now. and also to run the tests more easily locally as well. 

or should i better wait with the merge?

**Comment by rpkoller** [comment]
i'll merge the PR into the branch and will create a few follow up commits to the branch. i've managed to create exec host pre start hooks that grep the version number of the arangodb image that is set in the docker compose for arangodb. in the next step i insert that version number in a curl of docker-entrypoint. and that downloaded docker entrypoint then gets added the chmod line. thanks @rfay!

**Pull request merged**
